# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Bayesian RL'
tagline:          'Bayesian Reinforcement Learning'
description:      'Probabilistic and Bayesian methods for Reinforcement Learning, Control and Active Inference. A collection of materials related to my thesis'
url:              https://bayesianrl.github.io
baseurl:          https://bayesianrl.github.io/

author:
  name:           'Amirabbas Asadi'
  url:            https://www.linkedin.com/in/amirabbas-asadi/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb